{pkgs}: {
  deps = [
    pkgs.docker
    pkgs.android-tools
    pkgs.jdk
    pkgs.coreutils
    pkgs.gcc
    pkgs.python39
    pkgs.pkg-config
    pkgs.mtdev
    pkgs.libcxx
    pkgs.SDL2_ttf
    pkgs.SDL2_mixer
    pkgs.SDL2_image
    pkgs.SDL2
    pkgs.buildozer
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
  ];
}
